# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fumery/prog/C++/BruteForce

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fumery/prog/C++/BruteForce

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fumery/prog/C++/BruteForce/CMakeFiles /home/fumery/prog/C++/BruteForce/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fumery/prog/C++/BruteForce/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bf

# Build rule for target.
Bf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bf
.PHONY : Bf

# fast build rule for target.
Bf/fast:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/build
.PHONY : Bf/fast

sources/arguments.o: sources/arguments.cpp.o

.PHONY : sources/arguments.o

# target to build an object file
sources/arguments.cpp.o:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/arguments.cpp.o
.PHONY : sources/arguments.cpp.o

sources/arguments.i: sources/arguments.cpp.i

.PHONY : sources/arguments.i

# target to preprocess a source file
sources/arguments.cpp.i:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/arguments.cpp.i
.PHONY : sources/arguments.cpp.i

sources/arguments.s: sources/arguments.cpp.s

.PHONY : sources/arguments.s

# target to generate assembly for a file
sources/arguments.cpp.s:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/arguments.cpp.s
.PHONY : sources/arguments.cpp.s

sources/bruteforce.o: sources/bruteforce.cpp.o

.PHONY : sources/bruteforce.o

# target to build an object file
sources/bruteforce.cpp.o:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/bruteforce.cpp.o
.PHONY : sources/bruteforce.cpp.o

sources/bruteforce.i: sources/bruteforce.cpp.i

.PHONY : sources/bruteforce.i

# target to preprocess a source file
sources/bruteforce.cpp.i:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/bruteforce.cpp.i
.PHONY : sources/bruteforce.cpp.i

sources/bruteforce.s: sources/bruteforce.cpp.s

.PHONY : sources/bruteforce.s

# target to generate assembly for a file
sources/bruteforce.cpp.s:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/bruteforce.cpp.s
.PHONY : sources/bruteforce.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/Bf.dir/build.make CMakeFiles/Bf.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Bf"
	@echo "... edit_cache"
	@echo "... sources/arguments.o"
	@echo "... sources/arguments.i"
	@echo "... sources/arguments.s"
	@echo "... sources/bruteforce.o"
	@echo "... sources/bruteforce.i"
	@echo "... sources/bruteforce.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

